{"value": "BEIJING-LCG2"}
{"value": "BEgrid-ULB-VUB"}
{"value": "BUDAPEST"}
{"value": "BY-NCPHEP"}
{"value": "Baylor-Tier3"}
{"value": "BelGrid-UCL"}
{"value": "CERN-PROD"}
{"value": "CERN-PROD-AI"}
{"value": "CERN-PROD-HLT"}
{"value": "CIEMAT-LCG2"}
{"value": "CIT_CMS_T2"}
{"value": "CN-BEIJING-PKU"}
{"value": "CSCS-LCG2"}
{"value": "DESY-HH"}
{"value": "FIUPG"}
{"value": "FI_HIP_T2"}
{"value": "FLTECH"}
{"value": "FSU-HEP"}
{"value": "FZK-LCG2"}
{"value": "Firefly"}
{"value": "GLOW"}
{"value": "GR-05-DEMOKRITOS"}
{"value": "GR-06-IASA"}
{"value": "GR-07-UOI-HEPLAB"}
{"value": "GRIF"}
{"value": "GROW-PROD"}
{"value": "HEPGRID_UERJ"}
{"value": "HG-02-IASA"}
{"value": "Hephy-Vienna"}
{"value": "ICM"}
{"value": "IFCA-LCG2"}
{"value": "IFRU"}
{"value": "IN2P3-CC"}
{"value": "IN2P3-CC-T2"}
{"value": "IN2P3-IPNL"}
{"value": "IN2P3-IRES"}
{"value": "INDIACMS-TIFR"}
{"value": "INFN-BARI"}
{"value": "INFN-BOLOGNA-T3"}
{"value": "INFN-FIRENZE"}
{"value": "INFN-LNL-2"}
{"value": "INFN-MIB"}
{"value": "INFN-NAPOLI-CMS"}
{"value": "INFN-PERUGIA"}
{"value": "INFN-PISA"}
{"value": "INFN-ROMA1-CMS"}
{"value": "INFN-T1"}
{"value": "INFN-TRIESTE"}
{"value": "IR-IPM-HEP"}
{"value": "ITEP"}
{"value": "JINR-LCG2"}
{"value": "JINR-T1"}
{"value": "JINR-T1-DISK"}
{"value": "KR-KNU-T3"}
{"value": "KR_UOS_SSCC"}
{"value": "Kharkov-KIPT-LCG2"}
{"value": "LCG_KNU"}
{"value": "MIT_CMS"}
{"value": "MIT_CMS_T3"}
{"value": "MY-UPM-BIRUNI-01"}
{"value": "NCG-INGRID-PT"}
{"value": "NCP-LCG2"}
{"value": "NU Tier3"}
{"value": "NWICG_NDCMS"}
{"value": "NYSGRID_CORNELL_NYS1"}
{"value": "NZ-UOA"}
{"value": "Nebraska"}
{"value": "Princeton"}
{"value": "Purdue-Carter"}
{"value": "Purdue-Hansen"}
{"value": "Purdue-RCAC"}
{"value": "Purdue-Rossmann"}
{"value": "RAL-LCG2"}
{"value": "RAL-LCG2-DISK"}
{"value": "RRC-KI"}
{"value": "RU-Protvino-IHEP"}
{"value": "RWTH-Aachen"}
{"value": "Rice"}
{"value": "Ru-Troitsk-INR-LCG2"}
{"value": "SPRACE"}
{"value": "T0_CH_CERN"}
{"value": "T0_CH_CERN_Export"}
{"value": "T0_CH_CERN_MSS"}
{"value": "T1_CH_CERN"}
{"value": "T1_CH_CERN_Buffer"}
{"value": "T1_CH_CERN_MSS"}
{"value": "T1_DE_KIT"}
{"value": "T1_DE_KIT_Buffer"}
{"value": "T1_DE_KIT_Disk"}
{"value": "T1_DE_KIT_MSS"}
{"value": "T1_ES_PIC"}
{"value": "T1_ES_PIC_Buffer"}
{"value": "T1_ES_PIC_Disk"}
{"value": "T1_ES_PIC_MSS"}
{"value": "T1_FR_CCIN2P3"}
{"value": "T1_FR_CCIN2P3_Buffer"}
{"value": "T1_FR_CCIN2P3_MSS"}
{"value": "T1_IT_CNAF"}
{"value": "T1_IT_CNAF_Buffer"}
{"value": "T1_IT_CNAF_Disk"}
{"value": "T1_IT_CNAF_MSS"}
{"value": "T1_RU_JINR"}
{"value": "T1_RU_JINR_Buffer"}
{"value": "T1_RU_JINR_Disk"}
{"value": "T1_RU_JINR_MSS"}
{"value": "T1_RU_JINR_Stage"}
{"value": "T1_TW_ASGC"}
{"value": "T1_TW_ASGC_Buffer"}
{"value": "T1_TW_ASGC_MSS"}
{"value": "T1_TW_ASGC_Stage"}
{"value": "T1_UK_RAL"}
{"value": "T1_UK_RAL_Buffer"}
{"value": "T1_UK_RAL_Disk"}
{"value": "T1_UK_RAL_MSS"}
{"value": "T1_UK_RAL_Stage"}
{"value": "T1_US_FNAL"}
{"value": "T1_US_FNAL_Buffer"}
{"value": "T1_US_FNAL_Disk"}
{"value": "T1_US_FNAL_MSS"}
{"value": "T2-TH-CUNSTDA"}
{"value": "T2_AT_Vienna"}
{"value": "T2_BE_IIHE"}
{"value": "T2_BE_UCL"}
{"value": "T2_BR_SPRACE"}
{"value": "T2_BR_UERJ"}
{"value": "T2_CH_CERN"}
{"value": "T2_CH_CERN_AI"}
{"value": "T2_CH_CERN_HLT"}
{"value": "T2_CH_CSCS"}
{"value": "T2_CN_Beijing"}
{"value": "T2_DE_DESY"}
{"value": "T2_DE_RWTH"}
{"value": "T2_EE_Estonia"}
{"value": "T2_ES_CIEMAT"}
{"value": "T2_ES_IFCA"}
{"value": "T2_Estonia"}
{"value": "T2_FI_HIP"}
{"value": "T2_FR_CCIN2P3"}
{"value": "T2_FR_GRIF_IRFU"}
{"value": "T2_FR_GRIF_LLR"}
{"value": "T2_FR_IPHC"}
{"value": "T2_GR_Ioannina"}
{"value": "T2_HU_Budapest"}
{"value": "T2_IN_TIFR"}
{"value": "T2_IT_Bari"}
{"value": "T2_IT_Legnaro"}
{"value": "T2_IT_Pisa"}
{"value": "T2_IT_Rome"}
{"value": "T2_KR_KNU"}
{"value": "T2_MY_UPM_BIRUNI"}
{"value": "T2_PK_NCP"}
{"value": "T2_PL_Warsaw"}
{"value": "T2_PT_NCG_Lisbon"}
{"value": "T2_RU_IHEP"}
{"value": "T2_RU_INR"}
{"value": "T2_RU_ITEP"}
{"value": "T2_RU_JINR"}
{"value": "T2_RU_PNPI"}
{"value": "T2_RU_RRC_KI"}
{"value": "T2_RU_SINP"}
{"value": "T2_TH_CUNSTDA"}
{"value": "T2_TR_METU"}
{"value": "T2_TW_Taiwan"}
{"value": "T2_UA_KIPT"}
{"value": "T2_UK_London_Brunel"}
{"value": "T2_UK_London_IC"}
{"value": "T2_UK_SGrid_Bristol"}
{"value": "T2_UK_SGrid_RALPP"}
{"value": "T2_US_Caltech"}
{"value": "T2_US_Florida"}
{"value": "T2_US_MIT"}
{"value": "T2_US_Nebraska"}
{"value": "T2_US_Purdue"}
{"value": "T2_US_UCSD"}
{"value": "T2_US_Vanderbilt"}
{"value": "T2_US_Wisconsin"}
{"value": "T3_BY_NCPHEP"}
{"value": "T3_CH_PSI"}
{"value": "T3_CN_PKU"}
{"value": "T3_CO_Uniandes"}
{"value": "T3_ES_Oviedo"}
{"value": "T3_EU_Parrot"}
{"value": "T3_FR_IPNL"}
{"value": "T3_GR_Demokritos"}
{"value": "T3_GR_IASA"}
{"value": "T3_GR_IASA_GR"}
{"value": "T3_GR_IASA_HG"}
{"value": "T3_IR_IPM"}
{"value": "T3_IT_Bologna"}
{"value": "T3_IT_Firenze"}
{"value": "T3_IT_MIB"}
{"value": "T3_IT_Napoli"}
{"value": "T3_IT_Perugia"}
{"value": "T3_IT_Trieste"}
{"value": "T3_KR_KNU"}
{"value": "T3_KR_UOS"}
{"value": "T3_MX_Cinvestav"}
{"value": "T3_NZ_UOA"}
{"value": "T3_RU_FIAN"}
{"value": "T3_TW_NCU"}
{"value": "T3_TW_NTU_HEP"}
{"value": "T3_UK_London_QMUL"}
{"value": "T3_UK_London_RHUL"}
{"value": "T3_UK_London_UCL"}
{"value": "T3_UK_SGrid_Oxford"}
{"value": "T3_UK_ScotGrid_ECDF"}
{"value": "T3_UK_ScotGrid_GLA"}
{"value": "T3_US_Baylor"}
{"value": "T3_US_Brown"}
{"value": "T3_US_Colorado"}
{"value": "T3_US_Cornell"}
{"value": "T3_US_FIT"}
{"value": "T3_US_FIU"}
{"value": "T3_US_FNALLPC"}
{"value": "T3_US_FNALXEN"}
{"value": "T3_US_FSU"}
{"value": "T3_US_JHU"}
{"value": "T3_US_Kansas"}
{"value": "T3_US_MIT"}
{"value": "T3_US_Minnesota"}
{"value": "T3_US_NU"}
{"value": "T3_US_NotreDame"}
{"value": "T3_US_OSU"}
{"value": "T3_US_Omaha"}
{"value": "T3_US_Parrot"}
{"value": "T3_US_ParrotTest"}
{"value": "T3_US_Princeton"}
{"value": "T3_US_Princeton_ICSE"}
{"value": "T3_US_PuertoRico"}
{"value": "T3_US_Rice"}
{"value": "T3_US_Rutgers"}
{"value": "T3_US_TAMU"}
{"value": "T3_US_TTU"}
{"value": "T3_US_UCD"}
{"value": "T3_US_UCR"}
{"value": "T3_US_UIowa"}
{"value": "T3_US_UMD"}
{"value": "T3_US_UMiss"}
{"value": "T3_US_UTENN"}
{"value": "T3_US_UVA"}
{"value": "T3_US_Vanderbilt_EC2"}
{"value": "TAMU_BRAZOS"}
{"value": "TR-03-METU"}
{"value": "TW-FTT"}
{"value": "TW-NCUHEP"}
{"value": "TW-NTU-HEP"}
{"value": "Taiwan-LCG2"}
{"value": "UCD"}
{"value": "UCR-HEP"}
{"value": "UCSDT2"}
{"value": "UCSDT2-B"}
{"value": "UColorado_HEP"}
{"value": "UFlorida-HPC"}
{"value": "UKI-LT2-Brunel"}
{"value": "UKI-LT2-IC-HEP"}
{"value": "UKI-LT2-QMUL"}
{"value": "UKI-LT2-RHUL"}
{"value": "UKI-LT2-UCL-HEP"}
{"value": "UKI-SCOTGRID-ECDF"}
{"value": "UKI-SCOTGRID-GLASGOW"}
{"value": "UKI-SOUTHGRID-BRIS-HEP"}
{"value": "UKI-SOUTHGRID-OX-HEP"}
{"value": "UKI-SOUTHGRID-RALPP"}
{"value": "UMN-CMS"}
{"value": "UMissHEP"}
{"value": "UNIANDES"}
{"value": "UOGRID"}
{"value": "USCMS-FNAL-LPC"}
{"value": "USCMS-FNAL-WC1"}
{"value": "USCMS-FNAL-WC1-DISK"}
{"value": "USCMS-FNAL-XEN"}
{"value": "UVA-HEP"}
{"value": "Vanderbilt"}
{"value": "Vanderbilt_EC2"}
{"value": "brown-cms-new"}
{"value": "cinvestav"}
{"value": "osu-cms"}
{"value": "pic"}
{"value": "ru-Moscow-FIAN-LCG2"}
{"value": "ru-Moscow-SINP-LCG2"}
{"value": "ru-PNPI"}
{"value": "rutgers-cms"}
{"value": "t3euparrot"}
{"value": "t3usparrot"}
{"value": "t3usparrottest"}
{"value": "ttu-antaeus"}
{"value": "umd-cms"}
{"value": "uprm-cms"}
