{"value": "ALLGROUP"}
{"value": "Analysis"}
{"value": "AnalysisOps"}
{"value": "Any"}
{"value": "B2G"}
{"value": "BoostedTop"}
{"value": "Bphys"}
{"value": "Btag"}
{"value": "COMMON"}
{"value": "CSA07"}
{"value": "DPG"}
{"value": "DataOOps"}
{"value": "DataOps"}
{"value": "Diffraction"}
{"value": "EWK"}
{"value": "Egamma"}
{"value": "FastSim"}
{"value": "Generator"}
{"value": "Generators"}
{"value": "HCAL"}
{"value": "HI"}
{"value": "HeavyIon"}
{"value": "HeavyIonPhysics"}
{"value": "Higgs"}
{"value": "Individual"}
{"value": "JetMet"}
{"value": "Maarten"}
{"value": "Muons"}
{"value": "NoGroup"}
{"value": "OnSel"}
{"value": "PFlowTau"}
{"value": "PhysVal"}
{"value": "Physics"}
{"value": "QCD"}
{"value": "RelVal"}
{"value": "SUSY"}
{"value": "SUSYBSM"}
{"value": "TEST"}
{"value": "TOP"}
{"value": "Tier0"}
{"value": "Top"}
{"value": "Tracker"}
{"value": "Trigger"}
{"value": "UCSD"}
{"value": "b-physics"}
{"value": "b-tagging"}
{"value": "data"}
{"value": "dataOps"}
{"value": "e-gamma_ecal"}
{"value": "ewk"}
{"value": "exotica"}
{"value": "forward"}
{"value": "heavy-ions"}
{"value": "higgs"}
{"value": "jets-met_hcal"}
{"value": "muon"}
{"value": "susy"}
{"value": "tau-pflow"}
{"value": "test"}
{"value": "top"}
{"value": "tracker-pog"}
