{"value": "ALCAPROMPT"}
{"value": "ALCARECO"}
{"value": "AOD"}
{"value": "AODSIM"}
{"value": "CRAP"}
{"value": "DAVE"}
{"value": "DBS3_DEPLOYMENT_TEST_TIER"}
{"value": "DIGI"}
{"value": "DIGI-RECO"}
{"value": "DQM"}
{"value": "DQMROOT"}
{"value": "FEVT"}
{"value": "FEVTDEBUGHLT"}
{"value": "FEVTHLTALL"}
{"value": "GEN"}
{"value": "GEN-RAW"}
{"value": "GEN-RAWDEBUG"}
{"value": "GEN-SIM"}
{"value": "GEN-SIM-DIGI"}
{"value": "GEN-SIM-DIGI-HLTDEBUG"}
{"value": "GEN-SIM-DIGI-HLTDEBUG-RECO"}
{"value": "GEN-SIM-DIGI-RAW"}
{"value": "GEN-SIM-DIGI-RAW-HLTDEBUG"}
{"value": "GEN-SIM-DIGI-RAW-HLTDEBUG-RECO"}
{"value": "GEN-SIM-DIGI-RAW-RECO"}
{"value": "GEN-SIM-DIGI-RECO"}
{"value": "GEN-SIM-DIGI-RECODEBUG"}
{"value": "GEN-SIM-RAW"}
{"value": "GEN-SIM-RAW-HLT"}
{"value": "GEN-SIM-RAW-HLTDEBUG"}
{"value": "GEN-SIM-RAW-HLTDEBUG-RECO"}
{"value": "GEN-SIM-RAW-HLTDEBUG-RECODEBUG"}
{"value": "GEN-SIM-RAW-RECO"}
{"value": "GEN-SIM-RAWDEBUG"}
{"value": "GEN-SIM-RECO"}
{"value": "GEN-SIM-RECODEBUG"}
{"value": "HLT"}
{"value": "HLTDEBUG"}
{"value": "HLY"}
{"value": "LHE"}
{"value": "RAW"}
{"value": "RAW-HLT"}
{"value": "RAW-HLY"}
{"value": "RAW-RECO"}
{"value": "RAW-RECOSIMHLT"}
{"value": "RAWDEBUG"}
{"value": "RAWRECOSIMHLT"}
{"value": "RECO"}
{"value": "RECODEBUG"}
{"value": "RECOSIMHLT"}
{"value": "SIM"}
{"value": "USER"}
